### ISSUE TITLE
[Category] Renaming a category

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#153] opened 2023-09-29 12:20 UTC
If I for example, create category “5” and now just save it without finishing the new creation, the 3 file directories are already created in the background. If I now change the category to “5 Buxtehude”, these directories will also be created. However, the directory “5” remains in the system. Such directories must be deleted manually.

**Comment by MrMusic** [comment] 2023-10-02 09:57
I can confirm the following problem:
If the alias of a category is changed manually, the 'path' in the database is not adjusted. Alias and path should be the same and unique.
Therefore, deleting the category after changing the alias is no longer possible.

**Comment by Elfangor93** [comment] 2023-12-18 10:15
**Here are two problems**
- When renaming a category, the folder is not renamed.
- When renaming a category, the path in the database is not adjusted.

**Comment by AlexanderSupp** [comment] 2024-01-15 16:51
Problem is solved with PR #179

**Comment by AlexanderSupp** [comment] 2024-01-15 17:22
The issue #157 is not solved. 
But with the changes in this PR the situation is cleared, if we drop the copy function of categories.
If so, we can close the issue 157 and this PR is ready to merge into main.

**Comment by Elfangor93** [comment] 2024-01-27 10:41
Close this issue since PR https://github.com/JoomGalleryfriends/JG4-dev/pull/179 fixed this issue...

**Closed by Elfangor93** 2024-01-27 10:41 UTC
Labels: bug, prio-high
