### ISSUE TITLE
Migration can't finish

### ISSUE THREAD

**Issue by Manfwo** [JoomGalleryfriends/JG4-dev#256] opened 2024-08-09 08:07 UTC
I have migrated a database from Joomla V3 with over 16000 images. The migration of the folder and image gave no error. Workflow like your migration video. Version JG4-dev-4.0.0-alpha3.
Then I wanted to finish the migration without deleting the old data. An error occurred.

Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel::getParams(): Return value must be of type array, Joomla\Registry\Registry returned 

Call Stack
 	Function 	Location
1 	() 	JROOT/administrator/components/com_joomgallery/src/Model/MigrationModel.php:147
2 	Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->getParams() 	JROOT/libraries/src/MVC/View/AbstractView.php:152
3 	Joomla\CMS\MVC\View\AbstractView->get() 	JROOT/administrator/components/com_joomgallery/src/View/Migration/HtmlView.php:64
4 	Joomgallery\Component\Joomgallery\Administrator\View\Migration\HtmlView->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:660
5 	Joomla\CMS\MVC\Controller\BaseController->display() 	JROOT/administrator/components/com_joomgallery/src/Controller/DisplayController.php:119
6 	Joomgallery\Component\Joomgallery\Administrator\Controller\DisplayController->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:693
7 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/administrator/components/com_joomgallery/src/Dispatcher/Dispatcher.php:32
9 	Joomgallery\Component\Joomgallery\Administrator\Dispatcher\Dispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
10 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:143
11 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:186
12 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293
13 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:61
14 	require_once() 	JROOT/administrator/index.php:32 

In the Front-end I get the message: Joomgallery is not installed.

See also the migration database table.
![st4_joomgallery_migration ](https://github.com/user-attachments/assets/37c4692c-0921-488c-bb7a-f0008b431acb)

**Comment by MrMusic** [comment] 2024-08-13 10:03
>Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel::getParams(): Return value must be of type array, Joomla\Registry\Registry returned

I can confirm the problem. Due to this error, the migration cannot be completed "properly". So you have to go back one step and simply switch to the Joomla backend.
However, your categories and images should all have been migrated and be displayed normally.

**Comment by Manfwo** [comment] 2024-08-14 07:06
When I go to the backend, everything looks fine. Images and categories are migrated. When I go to the migration menu item, there is the option "Resume" or "Abort". Both lead to a crash.
Which step should I go back? 
If something has been fixed at this point, I will test the complete process again with the next update.

**Comment by MrMusic** [comment] 2024-09-07 12:50
Fixed with https://github.com/JoomGalleryfriends/JG4-dev/pull/258

**Closed by MrMusic** 2024-09-07 12:50 UTC
